### ISSUE TITLE
Module build failed: ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by iamsonivivek** [wallacyyy/webpack-heroku#5]
@wallacyyy ERROR in ./~/css-loader!./~/sass-loader!./src/styles/app.scss
Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/home/yuva/Desktop/Projects/Compartirespacios/FrontEnd/Heroku/webpack-heroku-master/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:157:31)
    at LazyResult.then (/home/yuva/Desktop/Projects/Compartirespacios/FrontEnd/Heroku/webpack-heroku-master/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at processCss (/home/yuva/Desktop/Projects/Compartirespacios/FrontEnd/Heroku/webpack-heroku-master/node_modules/css-loader/lib/processCss.js:198:5)
    at Object.module.exports (/home/yuva/Desktop/Projects/Compartirespacios/FrontEnd/Heroku/webpack-heroku-master/node_modules/css-loader/lib/loader.js:24:2)
 @ ./src/styles/app.scss 4:14-120

**Node -v : v0.10.25**
 **npm -v : 1.3.10**

**Comment by runiie** [comment]
@iamsonivivek Can you put an example of your problem in a public repo for reference ?
